### ISSUE TITLE
Need to Clarify Credits for the Logo

### ISSUE THREAD

**Issue by shervinafshar** [persian-computing/persian-computing.github.io#2]
We need to add some credits for the logo designer. I could do that myself and send a PR if I know what are your preferences. My suggestions are: 

- a dedicated page about the background of the logo and credits for it;
- a one-liner on the footer crediting the designer and linking to the page above;
- a one-liner in the license section of the github repo.

Please let me know what you think.

**Comment by behnam** [comment]
Thanks for filing this, @shervinafshar!

We had the meta for it on the old MediaWiki page, which is apparently lost now. I though I've sent an email to the P-C list about it, but couldn't find it today.

Anyways, I just created this page and added a single sentence: https://github.com/persian-computing/persian-computing.github.io/wiki/Community#logo

Could you please elaborate on the design, and possibly more details like the year of the work and copyright matters, yourself?

I think we can put the details on the Community wiki page, and a one-liner on the home page under License. What do you think?

**Comment by shervinafshar** [comment]
Actually, I didn't mean that I should be credited for the logo! :D. I added a bit of text and dropped a line to Behrad Javanbakht, sharing the link to the text with him. We could do the one-liner in the homepage later.

Thanks again.
